export const MENUITEMS = [
  {
    menutitle: "MAIN",
  },
  {
    path: `/dashboard`,
    title: "Dashboard",
    icon: "fe-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    menutitle: "Pages",
  },

  {
    path: `/dashboard/analytics`,
    title: "Analytics",
    icon: "fe-pie-chart",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },

  {
    tab: `enquiry`,
    title: "Enquiry",
    icon: "fe-inbox",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `basic-details`,
    title: "Basic Details",
    icon: "fe-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `location`,
    title: "Location",
    icon: "fe-map",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: false,
  },
  {
    tab: `working-hours`,
    title: "Working Hours",
    icon: "fe-calendar",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: false,
  },
  {
    tab: `accomodation`,
    title: "Accomodation",
    icon: "fe-layers",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: false,
  },
  {
    tab: `amenities`,
    title: "Amenities",
    icon: "fe-grid",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: false,
  },
  {
    tab: `teachers`,
    title: "Teachers",
    icon: "fe-user-check",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `courses`,
    title: "Courses",
    icon: "fe-book",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `gallery`,
    title: "Gallery",
    icon: "fe-image",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `reviews`,
    title: "Reviews",
    icon: "fe-thumbs-up",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `faqs`,
    title: "FAQ`s",
    icon: "fe-help-circle",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `certifications`,
    title: "Certifications",
    icon: "fe-award",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `hiring`,
    title: "Hirings",
    icon: "fe-briefcase",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    tab: `applications`,
    title: "Applications",
    icon: "fe-file-text",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    tab: `seo`,
    title: "SEO",
    icon: "fe-bar-chart",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
  {
    tab: `coupons`,
    title: "Coupons",
    icon: "fe-tag",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    online: true,
  },
];
