export const MENUITEMS = [
  {
    menutitle: "MAIN",
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },

  {
    path: `/dashboard`,
    title: "Dashboard",
    icon: "fe-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },

  {
    menutitle: "Pages",
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },
  {
    title: "Users",
    icon: "fe-users",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin"],
    children: [
      {
        path: `/dashboard/user`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "User List",
      },
      {
        path: `/dashboard/user/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create User",
      },
    ],
  },
  {
    title: "Status",
    icon: "fe-bar-chart",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor"],
    children: [
      {
        path: `/dashboard/status`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Status List",
      },
      {
        path: `/dashboard/status/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Status",
      },
    ],
  },
  {
    title: "Course",
    icon: "fe-cpu",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    role: ["Super Admin", "Editor"],
    dirchange: false,
    children: [
      {
        path: `/dashboard/course`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Course List",
      },
      {
        path: `/dashboard/course/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Course",
      },
    ],
  },
  {
    title: "Category",
    icon: "fe-database",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor"],
    children: [
      {
        path: `/dashboard/category`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Category List",
      },
      {
        path: `/dashboard/category/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Category",
      },
    ],
  },
  {
    title: "Property",
    icon: "fe-grid",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor", "Property Manager"],
    children: [
      {
        path: `/dashboard/property`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Property List",
      },
      {
        path: `/dashboard/property/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Property",
      },
    ],
  },
  {
    title: "Enquiry",
    icon: "fe-list",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin"],
    children: [
      {
        path: `/dashboard/enquiry`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Enquiry",
      },
      {
        path: `/dashboard/enquiry/archive`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Archived Enquiry",
      },
    ],
  },
];
