import ALLImages from "../Imagesdata";

export const ItemData =
  [
    {
      id: 1,
      PREVIEW: ALLImages('pngs9'),
      TITLE: "Bracelets",
      PRICE: "$16,599",
      PRICES: "$19,799",
      IMG: [
        { "img": ALLImages("pngs9") },
        { "img": ALLImages("pngs91") },
        { "img": ALLImages("pngs92") },
      ],
      STATUS: "stock ",
      bgColor: "success",
    },
    {
      id: 2,
      PREVIEW: ALLImages('pngs1'),
      TITLE: "Cup",
      PRICE: "$529",
      PRICES: "$799",
      IMG: [
        { "img": ALLImages("pngs1") },
        { "img": ALLImages("pngs11") },
        { "img": ALLImages("pngs12") },
      ],
      STATUS: "instock",
      bgColor: "danger",
    },
    {
      id: 3,
      PREVIEW: ALLImages('pngs7'),
      TITLE: "Stool",
      PRICE: "$25,239",
      PRICES: "$34,399",
      IMG: [
        { "img": ALLImages("pngs7") },
        { "img": ALLImages("pngs71") },
        { "img": ALLImages("pngs72") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id: 4,
      PREVIEW: ALLImages('pngs2'),
      TITLE: "Video Game",
      PRICE: "$345",
      PRICES: "$459",
      IMG: [
        { "img": ALLImages("pngs2") },
        { "img": ALLImages("pngs21") },
        { "img": ALLImages("pngs22") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id: 5,
      PREVIEW: ALLImages('pngs4'),
      TITLE: "Flower Pot",
      PRICE: "$277",
      PRICES: "$456",
      IMG: [
        { "img": ALLImages("pngs4") },
        { "img": ALLImages("pngs41") },
        { "img": ALLImages("pngs42") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id: 6,
      PREVIEW: ALLImages('pngs8'),
      TITLE: "Watch",
      PRICE: "$567",
      PRICES: "$866",
      IMG: [
        { "img": ALLImages("pngs8") },
        { "img": ALLImages("pngs81") },
        { "img": ALLImages("pngs82") },
      ],
      STATUS: "instock",
      bgColor: "danger",
    },
    {
      id: 7,
      PREVIEW: ALLImages('pngs3'),
      TITLE: "Headset",
      PRICE: "$455",
      PRICES: "$567",
      IMG: [
        { "img": ALLImages("pngs3") },
        { "img": ALLImages("pngs33") },
        { "img": ALLImages("pngs32") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id: 8,
      PREVIEW: ALLImages('pngs5'),
      TITLE: "Chair",
      PRICE: "$345",
      PRICES: "$499",
      IMG: [
        { "img": ALLImages("pngs5") },
        { "img": ALLImages("pngs51") },
        { "img": ALLImages("pngs52") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id: 9,
      PREVIEW: ALLImages('pngs6'),
      TITLE: "Goggles",
      PRICE: "$543",
      PRICES: "$688",
      IMG: [
        { "img": ALLImages("pngs6") },
        { "img": ALLImages("pngs61") },
        { "img": ALLImages("pngs62") },
      ],
      STATUS: "stock",
      bgColor: "success",
    },
  ];
